// REST Client is a tool that allows you to make HTTP requests directly within Visual Studio Code.
// https://marketplace.visualstudio.com/items?itemName=humao.rest-client
// This file includes all requests available in AuthCompanion's Authentication API
@host = 127.0.0.1:3002/v1/auth
@user_email = testuser@authcompanion.com
@user_password = supersecretpassword

### Register a new user account
POST http://{{host}}/register
content-type: application/json

{
  "data": {
    "type": "users",
    "attributes": {
			"name": "Authy Person",
			"email": "{{user_email}}",
			"password": "{{user_password}}",
			"metadata": {
        "tenantID": "1234"
      }
    }
  }
}

### Login to the user account
# @name login
POST http://{{host}}/login
content-type: application/json

{
  "data": {
    "type": "users",
    "attributes": {
			"email": "{{user_email}}",
			"password": "{{user_password}}"
    }
  }
}

### Update the user account
@access_token = {{login.response.body.data.attributes.access_token}}
@refresh_token = {{login.response.headers.set-cookie}}
POST http://{{host}}/users/me
content-type: application/json
Authorization: Bearer {{access_token}}
Cookie: {{refresh_token}}

{
  "data": {
    "type": "users",
    "attributes": {
      "name": "Authy Person_updated_name"
    }
  }
}

### Recover a user account
POST http://{{host}}/recovery
content-type: application/json

{ 
  "email": "{{user_email}}"
}

### Regenerate user's refresh token
POST http://{{host}}/refresh
content-type: application/json
Cookie: {{refresh_token}}

{}

### Delete user's refresh token
DELETE http://{{host}}/refresh
content-type: application/json
Cookie: {{refresh_token}}

{}

### Get Server Config
GET http://{{host}}/config
content-type: application/json

{}
